In [1]:
import pandas as pd

In [4]:
# download bills from "anti-lgbtq bills" tab of https://bit.ly/lgbtq-legislation-2025
df = pd.read_csv('2025-bills.csv')

## preliminary exploration:
- df.shape, df.info(), df.head(), df.columns
- looking at individual columns
    - df['State']
    - df.value_counts('State')
    - df.value_counts('Bill Type')
    - df.value_counts('Youth State Risk')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1051 entries, 0 to 1050
Data columns (total 25 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   State                                1051 non-null   str
 1   Number                               1051 non-null   str
 2   Summary                              1051 non-null   str
 3   Bill Type                            1051 non-null   str
 4   Penalties                            231 non-null    str
 5   Date                                 1051 non-null   str
 6   Status                               1051 non-null   str
 7   Youth State Risk                     1045 non-null   str
 8   Adult State Risk                     1045 non-null   str
 9   Notes                                805 non-null    str
 10  URL                                  1051 non-null   str
 11  Sponsors                             1031 non-null   str
 12  Calendar                             411 non-null    str
 13  History                              1027 non-null   str
 14  Manual Status                        1051 non-null   str
 15  Change Hash                          1027 non-null   str
 16  Bill ID                              1027 non-null   float64
 17  PDF                                  1026 non-null   str
 18  Bill PDF                             0 non-null      float64
 19  Targets Gender Identity              850 non-null    str
 20  Targets Sexual Orientation           199 non-null    str
 21  Targets Minors                       893 non-null    str
 22  Targets Adults                       659 non-null    str
 23  Trans Exclusionary Sex Definiition?  503 non-null    str
 24  🔐 Softr Record ID                    1051 non-null   str
dtypes: float64(2), str(23)
memory usage: 205.4 KB

In [6]:
df.shape

(1051, 25)

In [7]:
df.head()

,State,Number,Summary,Bill Type,Penalties,Date,Status,Youth State Risk,Adult State Risk,Notes,...,Change Hash,Bill ID,PDF,Bill PDF,Targets Gender Identity,Targets Sexual Orientation,Targets Minors,Targets Adults,Trans Exclusionary Sex Definiition?,🔐 Softr Record ID
0,Alabama,HB107,"Sex-based terms, defined; vital statistics, re...",End Legal Recognition,NaN,2025-02-04,Pending House Judiciary,Worst,Worst,"A version of IWV's ""Stand with Women"" Act; com...",...,23d6e37c51a03dafd285a27028ec4b04,1956006.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,Binary Sex / Gamete Production,8qGxAarDi6LXSB5yFif6RA
1,Alabama,HB244,"Public K-12 education, discussions of gender i...",Don't Say Gay: K12 / Don't Say Trans: K12 / Pr...,NaN,2025-05-01,Read for the Second Time and placed on the Cal...,Worst,Worst,Extends existing K-5 Don't Say Gay or Trans ba...,...,0e9f3efeaa34d72cb7ffdb2d15b55cef,1965457.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,Y,Y,NaN,NaN,RiFmExye8zCKXaLFBEBsBL
2,Alabama,HB246,"Public schools, colleges, and universities; im...",Pronoun Ban / Forced Outing By Schools,NaN,2025-05-06,Currently Indefinitely Postponed,Worst,Worst,"K12/college, employees and students can misgen...",...,980b48edc0945eca0612d76d898f2a5c,1965693.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,Binary Sex / Gamete Production,TE8gD4mviSDvsVytF1eY6u
3,Alabama,HB4,"Crimes and offenses, further provides for obsc...",Censorship: Book Ban / Censorship: Drag Ban,Criminal: Misdemeanor/ Criminal: Felony,2025-02-04,Pending House Judiciary,Worst,Worst,Sexual conduct means: In K-12 public schools o...,...,56ffa299090fcee18f61127ba19e5fb6,1886100.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,NaN,NaN,8pvHY3tR4Wew3JiBcbYjz8
4,Alabama,HB418,Financial Institutions and Insurers; using soc...,Public Investment Restriction: Social Credit S...,NaN,2025-03-06,Pending House Financial Services,Worst,Worst,Refers to GAC of any age via a reference to st...,...,ad9fff7220127c0b7179ace25c339e0a,1994149.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,NaN,267FpqkB8xf2gHqw1tjPw2

In [9]:
df.columns

Index(['State', 'Number', 'Summary', 'Bill Type', 'Penalties', 'Date',
       'Status', 'Youth State Risk', 'Adult State Risk', 'Notes', 'URL',
       'Sponsors', 'Calendar', 'History', 'Manual Status', 'Change Hash',
       'Bill ID', 'PDF', 'Bill PDF', 'Targets Gender Identity',
       'Targets Sexual Orientation', 'Targets Minors', 'Targets Adults',
       'Trans Exclusionary Sex Definiition?', '🔐 Softr Record ID'],
      dtype='str')

In [10]:
df['State']

0       Alabama
1       Alabama
2       Alabama
3       Alabama
4       Alabama
         ...
1046    Wyoming
1047    Wyoming
1048    Wyoming
1049    Wyoming
1050    Wyoming
Name: State, Length: 1051, dtype: str

In [11]:
df.value_counts('State')

State
Texas             135
US                113
Missouri           70
Iowa               49
Oklahoma           36
West Virginia      34
Minnesota          32
Michigan           31
Montana            30
South Carolina     30
Tennessee          30
Mississippi        29
Connecticut        28
Idaho              27
Illinois           24
Wisconsin          20
Wyoming            20
Indiana            18
Kentucky           18
Oregon             15
Arizona            14
New Hampshire      14
North Carolina     14
Ohio               14
Pennsylvania       14
Arkansas           13
Georgia            13
Florida            12
South Dakota       11
Utah               11
Alabama             9
Maine               9
Maryland            9
New Mexico          9
North Dakota        9
Virginia            9
New York            8
Washington          8
Hawaii              7
Kansas              7
Massachusetts       7
California          6
Colorado            6
Puerto Rico         6
Alaska              5
Rhode Island        5
Louisiana           4
Nebraska            3
New Jersey          3
Nevada              2
Delaware            1
Name: count, dtype: int64

In [12]:
df.value_counts('Bill Type')

Bill Type
DEI Ban                                                                                                                                    76
Gender Affirming Care Ban: Minors                                                                                                          60
End Legal Recognition                                                                                                                      42
Censorship: Book Ban                                                                                                                       37
Sports Ban: K12 / Sports Ban: Colleges                                                                                                     36
                                                                                                                                           ..
Gender Affirming Care Ban: Public Funds / Don't Say Gay: Government / Don't Say Trans: Government / Gender Affirming Care Ban: Medicaid     1
Sports Ban: Elementary / Sports Ban: Colleges                                                                                               1
Trans Bathroom Ban: Public Properties / Prison Placement Ban / Trans Bathroom Ban: Colleges                                                 1
Censorship: Book Ban / Censorship: Drag Ban / Censorship: Online Obscenity / Broad Discrimination                                           1
Pronoun Ban / Forced Outing By Schools / Opt-Out LGBTQ Education                                                                            1
Name: count, Length: 298, dtype: int64

In [14]:
df['Youth State Risk']

0       Worst
1       Worst
2       Worst
3       Worst
4       Worst
        ...
1046    Worst
1047    Worst
1048    Worst
1049    Worst
1050    Worst
Name: Youth State Risk, Length: 1051, dtype: str

In [15]:
df.value_counts('Youth State Risk')

Youth State Risk
Worst            626
Do Not Travel    147
Moderate         144
Safest            72
Low               47
High               9
Name: count, dtype: int64

## creating a sub DataFrame
Taking a value "Worst" from the "Youth State Risk" colum to create a new sub-dataframe

worst = df['Youth State Risk'] == 'Worst'

In [18]:
df[worst]

,State,Number,Summary,Bill Type,Penalties,Date,Status,Youth State Risk,Adult State Risk,Notes,...,Change Hash,Bill ID,PDF,Bill PDF,Targets Gender Identity,Targets Sexual Orientation,Targets Minors,Targets Adults,Trans Exclusionary Sex Definiition?,🔐 Softr Record ID
0,Alabama,HB107,"Sex-based terms, defined; vital statistics, re...",End Legal Recognition,NaN,2025-02-04,Pending House Judiciary,Worst,Worst,"A version of IWV's ""Stand with Women"" Act; com...",...,23d6e37c51a03dafd285a27028ec4b04,1956006.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,Binary Sex / Gamete Production,8qGxAarDi6LXSB5yFif6RA
1,Alabama,HB244,"Public K-12 education, discussions of gender i...",Don't Say Gay: K12 / Don't Say Trans: K12 / Pr...,NaN,2025-05-01,Read for the Second Time and placed on the Cal...,Worst,Worst,Extends existing K-5 Don't Say Gay or Trans ba...,...,0e9f3efeaa34d72cb7ffdb2d15b55cef,1965457.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,Y,Y,NaN,NaN,RiFmExye8zCKXaLFBEBsBL
2,Alabama,HB246,"Public schools, colleges, and universities; im...",Pronoun Ban / Forced Outing By Schools,NaN,2025-05-06,Currently Indefinitely Postponed,Worst,Worst,"K12/college, employees and students can misgen...",...,980b48edc0945eca0612d76d898f2a5c,1965693.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,Binary Sex / Gamete Production,TE8gD4mviSDvsVytF1eY6u
3,Alabama,HB4,"Crimes and offenses, further provides for obsc...",Censorship: Book Ban / Censorship: Drag Ban,Criminal: Misdemeanor/ Criminal: Felony,2025-02-04,Pending House Judiciary,Worst,Worst,Sexual conduct means: In K-12 public schools o...,...,56ffa299090fcee18f61127ba19e5fb6,1886100.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,NaN,NaN,8pvHY3tR4Wew3JiBcbYjz8
4,Alabama,HB418,Financial Institutions and Insurers; using soc...,Public Investment Restriction: Social Credit S...,NaN,2025-03-06,Pending House Financial Services,Worst,Worst,Refers to GAC of any age via a reference to st...,...,ad9fff7220127c0b7179ace25c339e0a,1994149.0,https://alison.legislature.state.al.us/files/p...,NaN,Y,NaN,Y,Y,NaN,267FpqkB8xf2gHqw1tjPw2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,Wyoming,HB0335,Wyoming educational religious freedom act.,Religious Exemptions: Academic / Discriminatio...,NaN,2025-02-03,Did not Consider for Introduction,Worst,Worst,NaN,...,5083d442cb8cd9bfb1ccdece1dd34959,1946917.0,https://www.wyoleg.gov/2025/Introduced/HB0335.pdf,NaN,NaN,NaN,Y,NaN,NaN,DfsQeWPCfP7KWVc8xJTUR4
1047,Wyoming,SF0044,Fairness in sports-intercollegiate athletics.,Sports Ban: Colleges,Civil: Liability / Civil: Academic,2025-03-13,Assigned Chapter Number 144,Worst,Worst,Post-secondary; also blocks competing with oth...,...,c4fd25d8310bb296c0f2d3b7baa98017,1897115.0,https://www.wyoleg.gov/2025/Introduced/SF0044....,NaN,Y,NaN,NaN,Y,Biological Sex / Gamete Production / Binary Se...,CkGSMUTzTxHURhXWhdhkFN
1048,Wyoming,SF0062,Sex-designated facilities and public schools.,Trans Bathroom Ban: K12,Civil: Licensure / Civil: Liability,2025-03-03,Assigned Chapter Number 101,Worst,Worst,NaN,...,860fcfacedcd47a57001e014612251b6,1899711.0,https://www.wyoleg.gov/2025/Introduced/SF0062....,NaN,Y,NaN,Y,NaN,Gamete Production / Biological Sex / Binary Sex,LGAbyruzeevi5nQdL43ygZ
1049,Wyoming,SF0077,Compelled speech is not free speech.,Pronoun Ban,Civil: Liability,2025-02-27,Assigned Chapter Number 62,Worst,Worst,Ban for state agencies to require use of prefe...,...,e0588bdd8ec7426d2473173a469ebc7c,1900703.0,https://www.wyoleg.gov/2025/Introduced/SF0077....,NaN,Y,NaN,Y,Y,NaN,horoSFSczWdFYfsFXpACu
1050,Wyoming,SF0103,"Terminating and defunding diversity, equity an...",DEI Ban,NaN,2025-03-04,Governor Vetoed SEA No. 0061,Worst,Worst,"""gender dysphoria"" among enumerated items",...,940d79d8cadca81e2f7fb7ba51a4f01a,1911910.0,https://www.wyoleg.gov/2025/Introduced/SF0103....,NaN,Y,NaN,NaN,Y,NaN,KFH1iBeurQBb8KtoMz9rr1

## cleaning
- what kind of predictions could we make from the data?
  - think about which of these columns can be used to guess about
    another column.
    - Example:
    - what states are likely to have "Worst" risk?
- the decisions we make about prediction will affect the way we clean
  and process the dataset.

In [19]:
df["Bill Type"].value_counts()

Bill Type
DEI Ban                                                                                                                                    76
Gender Affirming Care Ban: Minors                                                                                                          60
End Legal Recognition                                                                                                                      42
Censorship: Book Ban                                                                                                                       37
Sports Ban: K12 / Sports Ban: Colleges                                                                                                     36
                                                                                                                                           ..
Gender Affirming Care Ban: Public Funds / Don't Say Gay: Government / Don't Say Trans: Government / Gender Affirming Care Ban: Medicaid     1
Sports Ban: Elementary / Sports Ban: Colleges                                                                                               1
Trans Bathroom Ban: Public Properties / Prison Placement Ban / Trans Bathroom Ban: Colleges                                                 1
Censorship: Book Ban / Censorship: Drag Ban / Censorship: Online Obscenity / Broad Discrimination                                           1
Pronoun Ban / Forced Outing By Schools / Opt-Out LGBTQ Education                                                                            1
Name: count, Length: 298, dtype: int64

In [20]:
df["Bill Type Raw"] = df["Bill Type"]

In [21]:
df.columns

Index(['State', 'Number', 'Summary', 'Bill Type', 'Penalties', 'Date',
       'Status', 'Youth State Risk', 'Adult State Risk', 'Notes', 'URL',
       'Sponsors', 'Calendar', 'History', 'Manual Status', 'Change Hash',
       'Bill ID', 'PDF', 'Bill PDF', 'Targets Gender Identity',
       'Targets Sexual Orientation', 'Targets Minors', 'Targets Adults',
       'Trans Exclusionary Sex Definiition?', '🔐 Softr Record ID',
       'Bill Type Raw'],
      dtype='str')

In [22]:
df["Bill Type"].str.split("/")

0                                 [End Legal Recognition]
1       [Don't Say Gay: K12 ,  Don't Say Trans: K12 , ...
2               [Pronoun Ban ,  Forced Outing By Schools]
3          [Censorship: Book Ban ,  Censorship: Drag Ban]
4       [Public Investment Restriction: Social Credit ...
                              ...
1046    [Religious Exemptions: Academic ,  Discriminat...
1047                               [Sports Ban: Colleges]
1048                            [Trans Bathroom Ban: K12]
1049                                        [Pronoun Ban]
1050                                            [DEI Ban]
Name: Bill Type, Length: 1051, dtype: object

In [32]:
df['Bill Type']

0                                   End Legal Recognition
1       Don't Say Gay: K12 / Don't Say Trans: K12 / Pr...
2                  Pronoun Ban / Forced Outing By Schools
3             Censorship: Book Ban / Censorship: Drag Ban
4       Public Investment Restriction: Social Credit S...
                              ...
1046    Religious Exemptions: Academic / Discriminatio...
1047                                 Sports Ban: Colleges
1048                              Trans Bathroom Ban: K12
1049                                          Pronoun Ban
1050                                              DEI Ban
Name: Bill Type, Length: 1051, dtype: str

In [71]:
df["bill_type_labels"] = df["Bill Type"].str.split("/").fillna("")

In [72]:
df['bill_type_labels']

0                                 [End Legal Recognition]
1       [Don't Say Gay: K12 ,  Don't Say Trans: K12 , ...
2               [Pronoun Ban ,  Forced Outing By Schools]
3          [Censorship: Book Ban ,  Censorship: Drag Ban]
4       [Public Investment Restriction: Social Credit ...
                              ...
1046    [Religious Exemptions: Academic ,  Discriminat...
1047                               [Sports Ban: Colleges]
1048                            [Trans Bathroom Ban: K12]
1049                                        [Pronoun Ban]
1050                                            [DEI Ban]
Name: bill_type_labels, Length: 1051, dtype: object

In [73]:
def clean_labels(labels):
    return [label.strip() for label in labels]

In [74]:
df["bill_type_labels"] = df["bill_type_labels"].apply(clean_labels)

In [76]:
df['bill_type_labels']

0                                 [End Legal Recognition]
1       [Don't Say Gay: K12, Don't Say Trans: K12, Pro...
2                 [Pronoun Ban, Forced Outing By Schools]
3            [Censorship: Book Ban, Censorship: Drag Ban]
4       [Public Investment Restriction: Social Credit ...
                              ...
1046    [Religious Exemptions: Academic, Discriminatio...
1047                               [Sports Ban: Colleges]
1048                            [Trans Bathroom Ban: K12]
1049                                        [Pronoun Ban]
1050                                            [DEI Ban]
Name: bill_type_labels, Length: 1051, dtype: object

In [79]:
print(df["Bill Type Raw"].iloc[0])
print(df["bill_type_labels"].iloc[0])

End Legal Recognition
['End Legal Recognition']

## "exploding" the dataset
- we want to add more rows for each record, so we can mark the label as "present" or "absent"

In [81]:
# use explode to pull out the individual labels (this will create more records)
labels = df["bill_type_labels"].explode()

In [82]:
labels

0             End Legal Recognition
1                Don't Say Gay: K12
1              Don't Say Trans: K12
1                       Pronoun Ban
1        Censorship: Pride Flag Ban
                   ...
1046    Discrimination in Education
1047           Sports Ban: Colleges
1048        Trans Bathroom Ban: K12
1049                    Pronoun Ban
1050                        DEI Ban
Name: bill_type_labels, Length: 1737, dtype: str

In [83]:
labels.value_counts()

bill_type_labels
End Legal Recognition                     112
DEI Ban                                   101
Gender Affirming Care Ban: Minors         100
Sports Ban: K12                            94
Sports Ban: Colleges                       75
                                         ...
Gender Affirming Care: Liability Law        1
Anti-LGBTQ Resolution: Pathologization      1
Don't Say Gay: Government                   1
Don't Say Trans: Government                 1
Sports Ban: Elementary                      1
Name: count, Length: 127, dtype: int64

In [91]:
labels_list = list(labels.unique())

In [92]:
labels_list

['End Legal Recognition',
 "Don't Say Gay: K12",
 "Don't Say Trans: K12",
 'Pronoun Ban',
 'Censorship: Pride Flag Ban',
 'Forced Misgendering',
 'Forced Outing By Schools',
 'Censorship: Book Ban',
 'Censorship: Drag Ban',
 'Public Investment Restriction: Social Credit Score',
 'Trans Bathroom Ban: K12',
 'Trans Segregation Bill',
 'Forced Outing: Healthcare',
 'Trans Bathroom Ban: Public Properties',
 'Trans Bathroom Ban: Colleges',
 'Sports Ban: K12',
 'Censorship: Online Obscenity',
 'Appropriations',
 'Gender Affirming Care Ban: Public Funds',
 'Public Investment Restriction: Anti-Boycotts',
 'Forced Outing',
 'Birth Certificate or Identification Change Ban',
 'Gender Marker Change Ban',
 'DEI Ban: Government Entities',
 'DEI Ban: Colleges',
 'DEI Ban: Public Funds',
 'DEI Ban',
 'Gender Affirming Care Ban: Liability Law',
 'Gender Affirming Care Ban: Minors',
 'Censorship: KOSA-Type Social Media Law',
 'Religious Exemptions: Marriage',
 'Religious Exemptions: Trans DNE',
 'Social Transitioning Ban',
 'Religious Exemptions: Adoption and Foster Care',
 'Child Custody Bill',
 'Religious Exemptions: Medical',
 'Trans Bathroom Ban: Prisons',
 'Prison Placement Ban',
 'Opt-Out LGBTQ Education',
 'Sports Ban: Colleges',
 'Sports Ban:K12',
 'Gender Affirming Care Ban: Medicaid',
 'Sports Ban: Secondary',
 'Trans Bathroom Ban: Public Accommodations',
 'Sports Ban: Non-Academic',
 'Discrimination in Healthcare',
 'Discrimination in Education',
 'Broad Discrimination',
 'Pathologization',
 'Gender Affirming Care Ban: Prisoners',
 'Censorship: Book Ban: K12',
 'Religious Exemptions: RFRA',
 'Religious Exemptions: Academic',
 'Opt-In LGBTQ Education',
 'Trans Bathroom Ban',
 "Don't Say Gay: Elementary",
 "Don't Say Trans: Elementary",
 'Anti-LGBTQ Resolution: Athletics',
 'Anti-LGBTQ Resolution: Colleges',
 'Same-Sex Marriage Discrimination',
 'Religious Exemptions',
 'Gender Affirming Care Ban',
 'Trans Surveillance Bill',
 'Gender Affirming Care: Controlled Substance',
 'Gender Affrming Care Ban: Minors',
 'Trans Bathroom Ban: Public Facilities',
 'Child Custody Law',
 'LGBTQ "Grooming" Bill',
 "Don't Say Systemic Biases: K12",
 'Discrimination in Employment',
 'Discrimination in Housing',
 'Discrimination in Public Accommodations',
 'Repeal Pro-LGBTQ Laws',
 'Public Investment Restriction: ESG Funds Ban',
 "Don't Say Trans: Secondary",
 'Trans Bathroom Ban: Public Spaces',
 'Social Transition Ban',
 'Conversion Therapy Legalization',
 'Forced Outing by Schools',
 'Gender Affirming Care Ban: Detransition Coverage Requirements',
 'Trans Bathrom Ban: Colleges',
 'Sports Ban: Public Funds',
 "Don't Say Trans: Colleges",
 'Discrimination in Credit',
 'DEI Ban: K12',
 'Obscentity Law',
 'Anti-LGBTQ Resolution: Marriage',
 'Anti-LGBTQ Resolution: K12',
 'Gender Affirming Care Ban: Adults',
 'Resolution',
 'Constitutional Ammendment',
 'Opt-In LGBTQ Instruction',
 'Gender Affirming Care Ban: Liability',
 'Trans Child Abuse',
 'Sports Ban',
 'Censorship: Book Ban: Public Libraries',
 'Gender Affirming Care Ban: LIability Law',
 'Legal Electoral Discrimination',
 'Anti-LGBTQ+ Holiday',
 'Recognition',
 "Don't Say Gay",
 "Don't Say Trans",
 'Gender Affirming Care Ban: Insurance Prohibition',
 'Gender Affirming Care Ban: Detrans Coverage',
 'Religious Exemptions: PFCGDA',
 'Commissions, Task Forces, and Studies',
 'Anti-LGBTQ Resolution',
 "Don't Say Gay: Colleges",
 "Don't Say Systemic Biases: Colleges",
 'Gender Affirming Care Ban: All Ages',
 'Pronoun Ban: Colleges',
 'Anti-Abortion',
 'Military Discrimination',
 'Religious Exemptions: MRFA',
 'Sports Ban K12: Sports Ban: Colleges',
 'Gender Affirming Care Ban:  Minors',
 'Anti-LGBTQ Resolution: Healthcare',
 'Prisoner Discrimination',
 'DEI ban',
 'Anti-LGBTQ Resolution: Athletics Anti-LGBTQ Resolution: Colleges',
 'Gender Affirming Care Ban:  Medicaid',
 'Gender Affirming Care Ban: Young Adult',
 'Gender Affirming Care: Liability Law',
 'Anti-LGBTQ Resolution: Pathologization',
 "Don't Say Gay: Government",
 "Don't Say Trans: Government",
 'Sports Ban: Elementary']

## formatting data for training
- we will put the data into a matrix with positive labels (1) to mark the presence of a specific label
- do to so, we use the MultiLabelBinarizer class from the sklearn library. This class allows us to "binarize" the data, adding 1s where instances of the data are positive.

In [93]:
from sklearn.preprocessing import MultiLabelBinarizer

In [94]:
mlb = MultiLabelBinarizer()

In [95]:
Y = mlb.fit_transform(df["bill_type_labels"])

In [96]:
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1051, 127))

In [97]:
mlb.classes_

array(['Anti-Abortion', 'Anti-LGBTQ Resolution',
       'Anti-LGBTQ Resolution: Athletics',
       'Anti-LGBTQ Resolution: Athletics Anti-LGBTQ Resolution: Colleges',
       'Anti-LGBTQ Resolution: Colleges',
       'Anti-LGBTQ Resolution: Healthcare', 'Anti-LGBTQ Resolution: K12',
       'Anti-LGBTQ Resolution: Marriage',
       'Anti-LGBTQ Resolution: Pathologization', 'Anti-LGBTQ+ Holiday',
       'Appropriations', 'Birth Certificate or Identification Change Ban',
       'Broad Discrimination', 'Censorship: Book Ban',
       'Censorship: Book Ban: K12',
       'Censorship: Book Ban: Public Libraries', 'Censorship: Drag Ban',
       'Censorship: KOSA-Type Social Media Law',
       'Censorship: Online Obscenity', 'Censorship: Pride Flag Ban',
       'Child Custody Bill', 'Child Custody Law',
       'Commissions, Task Forces, and Studies',
       'Constitutional Ammendment', 'Conversion Therapy Legalization',
       'DEI Ban', 'DEI Ban: Colleges', 'DEI Ban: Government Entities',
       'DEI Ban: K12', 'DEI Ban: Public Funds', 'DEI ban',
       'Discrimination in Credit', 'Discrimination in Education',
       'Discrimination in Employment', 'Discrimination in Healthcare',
       'Discrimination in Housing',
       'Discrimination in Public Accommodations', "Don't Say Gay",
       "Don't Say Gay: Colleges", "Don't Say Gay: Elementary",
       "Don't Say Gay: Government", "Don't Say Gay: K12",
       "Don't Say Systemic Biases: Colleges",
       "Don't Say Systemic Biases: K12", "Don't Say Trans",
       "Don't Say Trans: Colleges", "Don't Say Trans: Elementary",
       "Don't Say Trans: Government", "Don't Say Trans: K12",
       "Don't Say Trans: Secondary", 'End Legal Recognition',
       'Forced Misgendering', 'Forced Outing', 'Forced Outing By Schools',
       'Forced Outing by Schools', 'Forced Outing: Healthcare',
       'Gender Affirming Care Ban',
       'Gender Affirming Care Ban:  Medicaid',
       'Gender Affirming Care Ban:  Minors',
       'Gender Affirming Care Ban: Adults',
       'Gender Affirming Care Ban: All Ages',
       'Gender Affirming Care Ban: Detrans Coverage',
       'Gender Affirming Care Ban: Detransition Coverage Requirements',
       'Gender Affirming Care Ban: Insurance Prohibition',
       'Gender Affirming Care Ban: LIability Law',
       'Gender Affirming Care Ban: Liability',
       'Gender Affirming Care Ban: Liability Law',
       'Gender Affirming Care Ban: Medicaid',
       'Gender Affirming Care Ban: Minors',
       'Gender Affirming Care Ban: Prisoners',
       'Gender Affirming Care Ban: Public Funds',
       'Gender Affirming Care Ban: Young Adult',
       'Gender Affirming Care: Controlled Substance',
       'Gender Affirming Care: Liability Law',
       'Gender Affrming Care Ban: Minors', 'Gender Marker Change Ban',
       'LGBTQ "Grooming" Bill', 'Legal Electoral Discrimination',
       'Military Discrimination', 'Obscentity Law',
       'Opt-In LGBTQ Education', 'Opt-In LGBTQ Instruction',
       'Opt-Out LGBTQ Education', 'Pathologization',
       'Prison Placement Ban', 'Prisoner Discrimination', 'Pronoun Ban',
       'Pronoun Ban: Colleges',
       'Public Investment Restriction: Anti-Boycotts',
       'Public Investment Restriction: ESG Funds Ban',
       'Public Investment Restriction: Social Credit Score',
       'Recognition', 'Religious Exemptions',
       'Religious Exemptions: Academic',
       'Religious Exemptions: Adoption and Foster Care',
       'Religious Exemptions: MRFA', 'Religious Exemptions: Marriage',
       'Religious Exemptions: Medical', 'Religious Exemptions: PFCGDA',
       'Religious Exemptions: RFRA', 'Religious Exemptions: Trans DNE',
       'Repeal Pro-LGBTQ Laws', 'Resolution',
       'Same-Sex Marriage Discrimination', 'Social Transition Ban',
       'Social Transitioning Ban', 'Sports Ban',
       'Sports Ban K12: Sports Ban: Colleges', 'Sports Ban: Colleges',
       'Sports Ban: Elementary', 'Sports Ban: K12',
       'Sports Ban: Non-Academic', 'Sports Ban: Public Funds',
       'Sports Ban: Secondary', 'Sports Ban:K12',
       'Trans Bathrom Ban: Colleges', 'Trans Bathroom Ban',
       'Trans Bathroom Ban: Colleges', 'Trans Bathroom Ban: K12',
       'Trans Bathroom Ban: Prisons',
       'Trans Bathroom Ban: Public Accommodations',
       'Trans Bathroom Ban: Public Facilities',
       'Trans Bathroom Ban: Public Properties',
       'Trans Bathroom Ban: Public Spaces', 'Trans Child Abuse',
       'Trans Segregation Bill', 'Trans Surveillance Bill'], dtype=object)